name: RealShopping
main: com.github.kuben.realshopping.RealShopping
version: 0.32

commands:
   rsenter:
      description: Enter a store. Use this command standing at the entrance.
      usage: /rsenter OR right click on glass standing at the entrance.
      permission: realshopping.rsenter
      permission-message: You don't have permission to use this command
   rspay:
      description: Pay for the things you have taken.
      usage: /rspay OR right click on a "cash register".
      permission: realshopping.rspay
      permission-message: You don't have permission to use this command
   rsexit:
      description: Leave a store.
      usage: /rsexit OR right click on glass standing at the exit.
      permission: realshopping.rsexit
      permission-message: You don't have permission to use this command
   rscost:
      description: Check how much you need to pay for your articles.
      usage: /rscost OR left click on a "cash register".
      permission: realshopping.rscost
      permission-message: You don't have permission to use this command
   rsprices:
      description: Look at the price list.
      usage: /rsprices [STORE] [PAGE]
      permission: realshopping.rsprices
      permission-message: You don't have permission to use this command
   rsstores:
      description: Manages your stores (and admin stores if you have permission).
      usage: /rsstores store [buyfor %_OF_SELL_PRICE|collect [-c] [AMOUNT]|ban PLAYER|unban PLAYER|kick [-o] PLAYER|startsale %_OFF [ITEMID[,ITEMID[,ITEMID...]]]|endsale]
      permission: realshopping.rsstores
      permission-message: You don't have permission to use this command
   rssetprices:
      description: Add/remove prices.
      usage: /rssetprices add|del [STORE] ITEM_ID[:COST]
      permission: realshopping.rssetprices
      permission-message: You don't have permission to use this command
   rssetchests:
      description: Manage self-refilling chests.
      usage: /rssetchests create|del|additems|delitems [ITEMID[,ITEMID[,ITEMID...]]]
      permission: realshopping.rssetchests
      permission-message: You don't have permission to use this command
   rssetstores:
      description: Add or remove player stores.
      usage: /rssetstores entrance|exit|createstore|delstore [NAME]
      permission: realshopping.rssetstores
      permission-message: You don't have permission to use this command
   rsset:
      description: Add or remove admin stores.
      usage: /rsset entrance|exit|createstore|delstore [NAME]
      permission: realshopping.rsset
      permission-message: You don't have permission to use this command
   rsshipped:
      description: Manages items shipped from stores.
      usage: /rsshipped [collect [ID] | inspect ID]
      permission: realshopping.rsshipped
      permission-message: You don't have permission to use this command
   rstplocs:
      description: Makes it possible for users to teleport to certain allowed areas from a store, if they have paid for their items.
      usage: /rstplocs setwhitelistmode|setblacklistmode|add RADIUS|remove|highlight
      permission: realshopping.rsallowedtplocs
      permission-message: You don't have permission to use this command
   rsunjail:
      description: Unjail a player and teleport him outside the store he stole from.
      usage: /rsunjail PLAYER
      permission: realshopping.rsunjail
      permission-message: You don't have permission to use this command
   rsreload:
      description: Reloads the config and saves the prices.xml
      usage: /rsreload
      permission: realshopping.rsreload
      permission-message: You don't have permission to use this command
   rsprotect:
      description: Makes chests which you can't open from outside of the store
      usage: /rsprotect add|remove
      permission: realshopping.rsprotect
      permission-message: You don't have permission to use this command
   realshopping:
      description: Prints some info about the mod, configuration.
      usage: /realshopping
      permission: realshopping.realshopping
      permission-message: You don't have permission to use this command
