/*
 * RealShopping Bukkit plugin for Minecraft
 * Copyright 2013 Jakub Fojt
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *     
 */

package com.github.kuben.realshopping;

import java.io.File;
import java.io.IOException;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;

public class LangPack {
	
	public static String UNIT;
	public static String THISCOMMANDCANNOTBEUSEDFROMCONSOLE;
	public static String REALSHOPPINGRELOADED;
	public static String YOUENTERED;
	public static String YOURENOTATTHEENTRANCEOFASTORE;
	public static String THEREARENOSTORESSET;
	public static String YOULEFT;
	public static String YOURENOTATTHEEXITOFASTORE;
	public static String YOUHAVENTPAIDFORALLYOURARTICLES;
	public static String YOURENOTINSIDEASTORE;
	public static String YOUCANTAFFORDTOBUYTHINGSFOR;
	public static String YOUBOUGHTSTUFFFOR;
	public static String THEREARENOPRICESSETFORTHISSTORE;
	public static String YOURARTICLESCOST;
	public static String TRYINGTOCHEATYOURWAYOUT;
	public static String HAVEFUNINHELL;
	public static String ENTRANCEVARIABLESETTO;
	public static String EXITVARIABLESETTO;
	public static String WASCREATED;
	public static String WASREMOVED;
	public static String WASNTFOUND;
	public static String YOUARENOTTHEOWNEROFTHISSTORE;
	public static String THERESNOENTRANCESET;
	public static String THERSNOEXITSET;
	public static String YOUHAVETOUSETHESTOREARGUMENTWHENEXECUTINGTHISCOMMANDFROMCONSOLE;
	public static String THEPAGENUMBERMUSTBE1ORHIGHER;
	public static String YOUHAVETOBEINASTOREIFNOTUSINGTHESTOREARGUMENT;
	public static String ISNOTAVALIDPAGENUMBER;
	public static String YOUHAVETOBEINASTORETOUSETHISCOMMANDWITHTWOARGUENTS;
	public static String YOUHAVETOUSEALLTHREEARGUMENTSWHENEXECUTINGTHISCOMMANDFROMCONSOLE;
	public static String PRICEFOR;
	public static String SETTO;
	public static String ISNOTAPROPER_FOLLOWEDBYTHEPRICE_;
	public static String REMOVEDPRICEFOR;
	public static String COULDNTFINDPRICEFOR;
	public static String DOESNTEXIST;
	public static String ISNOTAPROPER_;
	public static String YOUARENTPERMITTEDTOEMANAGETHISSTORE;
	public static String CHESTCREATED;
	public static String ACHESTALREADYEXISTSONTHISLOCATION;
	public static String CHESTREMOVED;
	public static String COULDNTFINDCHESTONTHISLOCATION;
	public static String ONLYADMINSTORESCANHAVESELFREFILLINGCHESTS;
	public static String ADDED;
	public static String REMOVED;
	public static String ITEMS;
	public static String THISCHESTDOESNTEXIST;
	public static String ONEORMOREOFTHEITEMIDSWERENOTINTEGERS;
	public static String YOUHAVETOBEINASTORETOUSETHISCOMMAND;
	public static String MOREITEMSONPAGE;
	public static String THEREARENTTHATMANYPAGES;
	public static String TRIEDTOSTEALFROMTHESTORE;
	public static String WASTELEPORTEDTOHELL;
	public static String CREATINGASTORECOSTS;
	public static String YOUWEREJAILED;
	public static String YOUARENOLONGERINJAIL;
	public static String UNJAILED;
	public static String ISNOTJAILED;
	public static String ISNOTONLINE;
	public static String WASJAILED;
	public static String YOUAREBANNEDFROM;
	public static String YOUDONTOWNTHEITEMSYOUWANTTOSELL;
	public static String ADDEDTOSELLLIST;
	public static String THISSTOREDOESNTBUY;
	public static String THISSTOREDOESNTBUYANYITEMS;
	public static String CANCELLEDSELLINGITEMS;
	public static String YOUDONTHAVEALLTHEITEMSYOUWANTEDTOSELL;
	public static String SOLD;
	public static String ITEMSFOR;
	public static String YOUCANTSHIPANEMPTYCART;
	public static String PACKAGEWAITINGTOBEDELIVERED;
	public static String YOUHAVENTBOUGHTANYTHING;
	public static String THERESNOPACKAGEWITHTHEID;
	public static String YOUHAVENTGOTANYITEMSWAITINGTOBEDELIVERED;
	public static String THEBLOCKYOUARESTANDINGONISNTACHEST;
	public static String THEREISA;
	public static String PCNTOFFSALEAT;
	public static String ONSALE;
	public static String STORE;
	public static String OWNEDBY;
	public static String BUYSFOR;
	public static String PCNTOFORIGINAL;
	public static String NOTBUYINGFROMPLAYERS;
	public static String YOUCANTUSEAVALUEBELLOW0;
	public static String YOUCANTUSEAVALUEOF0ORLESS;
	public static String YOUCANTUSEAVALUEOVER100;
	public static String YOUCANTUSEAVALUEOF100ORMORE;
	public static String NOITEMSARESOLDINTHESTORE;
	public static String SALEENDED;
	public static String HASA;
	public static String PCNTOFFSALERIGHTNOW;
	public static String PCNTOFF;
	public static String ISALREADYBANNEDFROMYOURSTORE;
	public static String ISNOLONGERBANNEDFROMYOURSTORE;
	public static String WASNTBANNEDFROMYOURSTORE;
	public static String BANNED;
	public static String FROMSTORE;
	public static String YOUDONTHAVEPERMISSIONTOMANAGETHATSTORE;
	public static String NOTHINGTOCOLLECT;
	public static String FILLEDCHESTWITH;
	public static String DROPPED;
	public static String YOUHAVEPACKAGESWITHIDS_;
	public static String YOUDONTHAVEANYPACKAGESTOPICKUP;
	public static String TOPICKUP;
	public static String YOUHAVETOSPECIFYTHEID_;
	public static String THECONTENTSOFTHEPACKAGEARE;
	public static String WHITELISTMODEALREADYSET;
	public static String BLACKLISTMODEALREADYSET;
	public static String SETWHITELISTMODE;
	public static String SETBLACKLISTMODE;
	public static String REMOVEDONEOFTHE;
	public static String TELEPORTLOCATIONS;
	public static String THEREISNO;
	public static String TELEPORTLOCATIONWITHITSCENTERHERE;
	public static String OLDRADIUSVALUE;
	public static String REPLACEDWITH;
	public static String TELEPORTLOCATIONWITHARADIUSOF;
	public static String ISNOTANINTEGER;
	public static String ISNOTAVALIDARGUMENT;
	public static String YOUARENTALLOWEDTOTELEPORTTHERE;
	public static String SELLINGTOSTORESISNOTENABLEDONTHISSERVER;
	public static String ISNOTINYOURSTORE;
	public static String WASKICKEDFROMYOURSTORE;
	public static String PLAYER;
	public static String ISNTONLINEKICK;
	public static String PLAYERSINSTORE;
	public static String STORENOTEMPTY;
	public static String PACKAGESENT;
	public static String FROM;
	public static String INWORLD;
	public static String YOUCANTUSETHATITEMINSTORE;
	public static String THISCHESTISPROTECTED;
	//v0.43
	public static String SELLTOSTORE;
	public static String ENABLEDNOTIFICATIONSFOR;
	public static String DISABLEDNOTIFICATIONSFOR;
	public static String USAGE;
	public static String NOTIFICATIONSARE;
	public static String ON;
	public static String OFF;
	public static String SKIPPSIGN;
	public static String YOUWONTGETNOTIFIEDWHENYOURSTORE;
	public static String BECOMESMOREORLESSPOPULAR;
	public static String YOUWILLGETNOTIFIEDWHENYOURSTORE;
	public static String BECOMESATLEAST;
	public static String PLACESMOREORLESSPOPULAR;
	public static String WHERETRESHOLDIS_;
	public static String ANDTHEPRICESWILLBE_;
	public static String WHERETRESHOLDIS_CHANGES_;
	public static String ANDPERCENTIS_;
	public static String AI_ISNOTENABLED_;
	public static String SETMINIMALANDMAXIMALPRICESFOR;
	public static String OLDPRICESREPLACEDWITHPRICESFROM;
	public static String OLDPRICESREPLACEDWITHTHELOWEST_;
	public static String CLEAREDALLPRICESFOR;
	public static String HASAMINIMALPRICEOF;
	public static String ANDAMAXIMALPRICEOF;
	public static String FOR;
	public static String DOESNTHAVEAMINIMALANDMAXIMALPRICEFOR;
	public static String CLEAREDMINIMALANDMAXIMALPRICESFOR;
	public static String DIDNTHAVEAMINIMALANDMAXIMALPRICEFOR;
	public static String ISNOTAPROPERARGUMENT;
	public static String YOUCANTNAMEASTORETHAT;
	public static String HIGHLIGHTED5LOCATIONSFOR5SECONDS;
	public static String NOLOCATIONSTOHIGHLIGHT;
	public static String THISCHESTISALREADYPROTECTED;
	public static String MADECHESTPROTECTED;
	public static String UNPROTECTEDCHEST;
	public static String THISCHESTISNTPROTECTED;
	public static String READINGDESCRIPTION;
	public static String THISISTHENEWESTVERSION;
	public static String SUCCESSFULUPDATE;
	public static String UPDATEFAILED;
	public static String YOUARENTPERMITTEDTOUSETHISCOMMAND;
	public static String YOUCANTCOLLECT_YOUDONOTOWN;
	public static String YOUCANTCOLLECT_SERVER;
	public static String THELASTHOUR;
	public static String YESTERDAY;
	public static String LASTWEEK;
	public static String LASTMONTH;
	public static String YOURSTORE;
	public static String ISNOWTHE;
	public static String SINCE;
	public static String PROVIDEROF;
	public static String RAISEDTHEPRICEFOR;
	public static String LOWEREDTHEPRICEFOR;
	public static String BY;
	public static String TO;
	public static String WENTFROMBEINGTHE;
	public static String THPROVIDEROF;
	public static String TONOTSELLINGANY;
	public static String SHIPPEDPACKAGESENT;
	public static String WITH;
	public static String YOUCANNOTDROPITEMS_;
	public static String YOUCANNOTEMPTYBUCKETS_;
	public static String YOUCANNOTCRAFTITEMS_;
	public static String SHOPPINGCARTSARENOTENABLED_;
	public static String SHIPPINGISNOTENABLED_;
	public static String YOUCANNOTOPENENDERCHESTS_;
	public static String RESTARTTHESERVER_VERSION;
	public static String OFRE_UPDATECOMMAND;
	public static String OFRE_UPDATEINFO;
	public static String REALSHOPPINGINITIALIZED;
	public static String REALSHOPPINGDISABLED;
	public static String BOUGHTSTUFFFOR;
	public static String FROMYOURSTORE;
	public static String OWNER;
	public static String CANTAFFORDTOBUYITEMSFROMYOUFOR;
	public static String WITHDRAWNFROMYOURACCOUNT;
	public static String YOUCANTAFFORDTOPAYTHEDELIVERYFEEOF;
	public static String USESLEFT;
	public static String PRICES;
	public static String RSSTORESHELP;
	public static String BUYFORHELP;
	public static String COLLECTHELP;
	public static String BANHELP;
	public static String UNBANHELP;
	public static String KICKHELP;
	public static String STARTSALEHELP;
	public static String STARTSALEHELP2;
	public static String ENDSALEHELP;
	public static String NOTIFICATIONSHELP;
	public static String ONCHANGEHELP;
	public static String SETDEFAULTPRICESFOR;
	public static String THEREARENODEFAULTPRICES;
	public static String QUITCONVERSATION;
	public static String WHICHFILEDOYOUWANTTOIMPORT_;
	public static String ERROR_NO_XLSX_;
	public static String INTHEMAINDIRECTORY;
	public static String INTHEREALSHOPPINGDIRECTORY;
	public static String TYPETHECORRESPONDINGNUMBER_;
	public static String TOCANCEL;
	public static String ERROR_INPUTISNOTAVALIDINTEGER;
	public static String CHOSENFILE;
	public static String TYPE;
	public static String TOIMPORT_USERDEFINED_;
	public static String TOIMPORT_PROPOSITION_;
	public static String WRONGFILECHOSEN;
	public static String IMPORTED;
	public static String PRICESASDEFAULT;
	public static String ERRORCOULDNTIMPORTPRICES;
	public static String DONE;
	public static String REALSHOPPINGUPDATEDTO;
	public static String X_ST;
	public static String X_ND;
	public static String X_RD;
	public static String X_TH;
	//v0.44
	public static String YOUWILLBENOTIFIEDIF;
	public static String LOSESGAINS;
	public static String PLACES;
	public static String THEPRICEWILLBELOWEREDINCREASED_;
	public static String PCNTIF;
	public static String WONTNOTIFY_;
	
	public static void initialize(String lang){
		THISCOMMANDCANNOTBEUSEDFROMCONSOLE = "This command cannot be used from console";
		REALSHOPPINGRELOADED = "RealShopping reloaded.";
		YOUCANTUSETHATITEMINSTORE = "You can't use that item in store.";
		THISCHESTISPROTECTED = "This chest is protected. You have to be inside a store to open it.";
		YOUENTERED = "You entered ";
		YOULEFT = "You left ";
		YOUAREBANNEDFROM = "You are banned from ";
		YOURENOTATTHEENTRANCEOFASTORE = "You're not at the entrance of a store.";
		YOURENOTATTHEEXITOFASTORE = "You're not at the exit of a store.";
		THEREARENOSTORESSET = "There are no stores set.";
		YOUHAVENTPAIDFORALLYOURARTICLES = "You haven't paid for all your articles.";
		YOURENOTINSIDEASTORE = "You're not inside a store.";
		YOUCANTAFFORDTOBUYTHINGSFOR = "You can't afford to buy things for: ";
		YOUBOUGHTSTUFFFOR = "You bought stuff for: ";
		THEREARENOPRICESSETFORTHISSTORE = "There are no prices set for this store.";
		YOURARTICLESCOST = "Your articles cost: ";
		YOUDONTOWNTHEITEMSYOUWANTTOSELL = "You don't own the item(s) you want to sell.";
		ADDEDTOSELLLIST = " added to to-sell list. Confirm sale by right-clicking the same block with no items. Cancel by left-clicking.";
		THISSTOREDOESNTBUY = "This store doesn't buy ";
		THISSTOREDOESNTBUYANYITEMS = "This store doesn't buy any items.";
		CANCELLEDSELLINGITEMS = "Cancelled selling items.";
		YOUDONTHAVEALLTHEITEMSYOUWANTEDTOSELL = "You don't have all the items you were going to sell. Cancelled sale.";
		SOLD = "Sold ";
		ITEMSFOR = " items for ";
		YOUCANTSHIPANEMPTYCART = "You can't ship an empty cart.";
		PACKAGEWAITINGTOBEDELIVERED = "Package waiting to be delivered. Use /rsshipped to pick up the package. You may need to pay a recieving fee.";
		YOUHAVENTBOUGHTANYTHING = "You haven't bought anything.";
		THERESNOPACKAGEWITHTHEID = "There's no package with the id ";
		YOUHAVENTGOTANYITEMSWAITINGTOBEDELIVERED = "You haven't got any items waiting to be delivered.";
		THEBLOCKYOUARESTANDINGONISNTACHEST = "The block you are standing on isn't a chest.";
		TRYINGTOCHEATYOURWAYOUT = "Trying to cheat your way out??";
		HAVEFUNINHELL = "Have fun in hell!";
		ENTRANCEVARIABLESETTO = "Entrance variable set to: ";
		EXITVARIABLESETTO = "Exit variable set to: ";
		WASCREATED = " was created.";
		WASREMOVED = " was removed.";
		WASNTFOUND = " wasn't found.";
		STORENOTEMPTY = "The store is not empty. You can kick players with /rsstores STORE kick PLAYER";
		YOUARENOTTHEOWNEROFTHISSTORE = "You are not the owner of this store.";
		THERESNOENTRANCESET = "There's no entrance set.";
		THERSNOEXITSET = "There's no exit set.";
		YOUHAVETOUSETHESTOREARGUMENTWHENEXECUTINGTHISCOMMANDFROMCONSOLE = "You have to use the 'store' argument when executing this command from console.";
		YOUHAVETOBEINASTOREIFNOTUSINGTHESTOREARGUMENT = "You have to be in a store if not using the 'store' argument.";
		THEPAGENUMBERMUSTBE1ORHIGHER = "The page number must be 1 or higher.";
		ISNOTAVALIDPAGENUMBER = " is not a valid page number.";
		YOUHAVETOBEINASTORETOUSETHISCOMMANDWITHTWOARGUENTS = "You have to be in a store to use this command with no arguments.";
		YOUHAVETOUSEALLTHREEARGUMENTSWHENEXECUTINGTHISCOMMANDFROMCONSOLE = "You have to use all three arguments when executing this command from console.";
		THEREISA = "There is a ";
		PCNTOFFSALEAT = "% off sale at ";
		ONSALE = " ON SALE!";
		PRICEFOR = "Price for ";
		SETTO = " set to: ";
		ISNOTAPROPER_FOLLOWEDBYTHEPRICE_ = " is not a proper argument, use a numeric ID of the item followed by a colon and the price. Example: '/rssetprices add 57:1000' to set the price for DIAMOND_BLOCK to 1000";
		ISNOTAPROPER_ = " is not a proper argument, use a numeric ID of the item instead. Example: '/rssetprices del 57' to remove the price for DIAMOND_BLOCK";
		REMOVEDPRICEFOR = "Removed price for: ";
		COULDNTFINDPRICEFOR = "Couldn't find price for: ";
		STORE = "Store ";
		OWNEDBY = " owned by ";
		BUYSFOR = "Buys for ";
		PLAYERSINSTORE = "Players in store:";
		PCNTOFORIGINAL = "% of original price.";
		NOTBUYINGFROMPLAYERS = "Not buying from players.";
		YOUCANTUSEAVALUEBELLOW0 = "You can't use a value bellow 0.";
		YOUCANTUSEAVALUEOF0ORLESS = "You can't use a value of 0 or less.";
		YOUCANTUSEAVALUEOVER100 = "You can't use a value over 100.";
		YOUCANTUSEAVALUEOF100ORMORE = "You can't use a value of 100 or more.";
		NOITEMSARESOLDINTHESTORE = "No items are sold in the store.";
		SALEENDED = "Sale ended.";
		HASA = "Has a ";
		PCNTOFFSALERIGHTNOW = "% off sale right now!";
		PCNTOFF = "% off ";
		ISALREADYBANNEDFROMYOURSTORE = " is already banned from your store.";
		ISNOLONGERBANNEDFROMYOURSTORE = " is no longer banned from your store.";
		WASNTBANNEDFROMYOURSTORE = " wasn't banned from your store.";
		BANNED = "Banned ";
		FROMSTORE = " from store.";
		ISNOTINYOURSTORE = " is not in your store.";
		WASKICKEDFROMYOURSTORE = " was kicked from your store.";
		PLAYER = "Player ";
		ISNTONLINEKICK = " isn't online. You can kick an offline player by adding the -o flag, BUT THEY WON'T BE TELEPORTED OUT OF THE STORE. Only use this if you're about to delete the store or if you know what you're doing.";
		YOUDONTHAVEPERMISSIONTOMANAGETHATSTORE = "You don't have permission to manage that store.";
		NOTHINGTOCOLLECT = "Nothing to collect.";
		FILLEDCHESTWITH = "Filled chest with ";
		DROPPED = "Dropped ";
		YOUHAVEPACKAGESWITHIDS_ = "You have packages with ids from 1 to ";
		YOUDONTHAVEANYPACKAGESTOPICKUP = "You don't have any packages to pick up.";
		TOPICKUP = " to pick up.";
		YOUHAVETOSPECIFYTHEID_ = "You have to specify the id of the package you want to inspect.";
		PACKAGESENT = "Package sent ";
		FROM = " from ";
		INWORLD = " in world ";
		THECONTENTSOFTHEPACKAGEARE = "The contents of the package are: ";
		YOUARENTPERMITTEDTOEMANAGETHISSTORE = "You aren't permitted to manage this store.";
		DOESNTEXIST = " doesn't exist.";
		CHESTCREATED = "Chest created.";
		CHESTREMOVED = "Chest removed.";
		ACHESTALREADYEXISTSONTHISLOCATION = "A chest already exists on this location.";
		COULDNTFINDCHESTONTHISLOCATION = "Couldn't find chest on this location.";
		ONLYADMINSTORESCANHAVESELFREFILLINGCHESTS = "Only admin stores can have self-refilling stores.";
		ADDED = "Added ";
		REMOVED = "Removed ";
		ITEMS = " items.";
		THISCHESTDOESNTEXIST = "This chest doensn't exist.";
		ONEORMOREOFTHEITEMIDSWERENOTINTEGERS = "One or more of the item IDs were not integers.";
		YOUHAVETOBEINASTORETOUSETHISCOMMAND = "You have to be in a store to use this command.";
		MOREITEMSONPAGE = "More items on page ";
		THEREARENTTHATMANYPAGES = "There aren't that many pages.";
		WHITELISTMODEALREADYSET = "Whitelist mode already set.";
		BLACKLISTMODEALREADYSET = "Blacklist mode already set.";
		SETWHITELISTMODE = "Set whitelist mode. Now listing ALLOWED teleport locations.";
		SETBLACKLISTMODE = "Set blacklist mode. Now listing FORBIDDEN teleport locations.";
		REMOVEDONEOFTHE = "Removed one of the ";
		TELEPORTLOCATIONS = " teleport locations.";
		THEREISNO = "There is no ";
		TELEPORTLOCATIONWITHITSCENTERHERE = " teleport location with its center here.";
		OLDRADIUSVALUE = "Old radius value ";
		REPLACEDWITH = " replaced with ";
		TELEPORTLOCATIONWITHARADIUSOF = " teleport location with a radius of ";
		TRIEDTOSTEALFROMTHESTORE = " tried to steal from the store.";
		WASTELEPORTEDTOHELL = " was teleported to hell.";
		CREATINGASTORECOSTS = "Creating a store costs ";
		YOUWEREJAILED = "You were sent to jail. Now wait for someone to unjail you.";
		WASJAILED = " was jailed.";
		YOUARENOLONGERINJAIL = "You are no longer in jail.";
		UNJAILED = "Unjailed ";
		ISNOTJAILED = " is not in jail.";
		ISNOTONLINE = " is not online.";
		ISNOTANINTEGER = " is not an integer.";
		ISNOTAVALIDARGUMENT = " is not a valid argument.";
		YOUARENTALLOWEDTOTELEPORTTHERE = "You aren't allowed to teleport there!";
		SELLINGTOSTORESISNOTENABLEDONTHISSERVER = "Selling to stores in not enabled on this server.";
		//v0.43
		SELLTOSTORE = "Sell to store";
		ENABLEDNOTIFICATIONSFOR = "Enabled notifications for ";
		DISABLEDNOTIFICATIONSFOR = "Disabled notifications for ";
		USAGE = "Usage: ";
		NOTIFICATIONSARE = "Notifications are ";
		ON = "on";
		OFF = "off";
		SKIPPSIGN = "(Skip the %-sign)";
		YOUWONTGETNOTIFIEDWHENYOURSTORE = "You won't get notified when your store ";
		BECOMESMOREORLESSPOPULAR = " becomes more or less popular.";
		YOUWILLGETNOTIFIEDWHENYOURSTORE = "You will get notified when your store ";
		BECOMESATLEAST = " becomes at least ";
		PLACESMOREORLESSPOPULAR = " places more or less popular.";
		WHERETRESHOLDIS_ = " where TRESHOLD is how many places your store needs to lose or gain for you to be notified.";
		ANDTHEPRICESWILLBE_ = " And the prices will be lowered or increased by ";
		WHERETRESHOLDIS_CHANGES_ = " where TRESHOLD is how many places your store needs to lose or gain for you to be for the changes to happen, ";
		ANDPERCENTIS_ = "and PERCENT is how many percent the prices will be lowered or increased.";
		AI_ISNOTENABLED_ = "Automatic store management is not enabled on this server.";
		SETMINIMALANDMAXIMALPRICESFOR = "Set minimal and maximal prices for ";
		OLDPRICESREPLACEDWITHPRICESFROM = "Old prices replaced with prices from ";
		OLDPRICESREPLACEDWITHTHELOWEST_ = "Old prices replaced with the lowest price of every item in every store.";
		CLEAREDALLPRICESFOR = "Cleared all prices for ";
		HASAMINIMALPRICEOF = " has a minimal price of ";
		ANDAMAXIMALPRICEOF = " and a maximal price of ";
		FOR = " for ";
		DOESNTHAVEAMINIMALANDMAXIMALPRICEFOR = " doesn't have a minimal and maximal price for ";
		CLEAREDMINIMALANDMAXIMALPRICESFOR = "Cleared minimal and maximal prices for ";
		DIDNTHAVEAMINIMALANDMAXIMALPRICEFOR = " didn't have a minimal and maximal price for ";
		ISNOTAPROPERARGUMENT = " is not a proper argument.";
		YOUCANTNAMEASTORETHAT = "You can't name a store that.";
		HIGHLIGHTED5LOCATIONSFOR5SECONDS = "Highlighted 5 locations for 5 seconds.";
		NOLOCATIONSTOHIGHLIGHT = "No locations to highlight.";
		THISCHESTISALREADYPROTECTED = "This chest is already protected.";
		MADECHESTPROTECTED = "Made chest protected.";
		UNPROTECTEDCHEST = "Unprotected chest.";
		THISCHESTISNTPROTECTED = "This chest isn't protected.";
		READINGDESCRIPTION = "Reading description...";
		THISISTHENEWESTVERSION = "This is the newest version.";
		SUCCESSFULUPDATE = "Successful update!";
		UPDATEFAILED = "Update failed.";
		YOUARENTPERMITTEDTOUSETHISCOMMAND = "You aren't permitted to use this command.";
		YOUCANTCOLLECT_YOUDONOTOWN = "You can't collect your items to a chest in a store you do not own.";
		YOUCANTCOLLECT_SERVER = "You can't collect your items to a chest on this server.";
		THELASTHOUR = "the last hour";
		YESTERDAY = " yesterday";
		LASTWEEK = "last week";
		LASTMONTH = "last month";
		YOURSTORE = "Your store ";
		ISNOWTHE = " is now the ";
		SINCE = " since ";
		PROVIDEROF = ") provider of ";
		RAISEDTHEPRICEFOR = "Raised the price for ";
		LOWEREDTHEPRICEFOR = "Lowered the price for ";
		BY = " by ";
		TO = " to ";
		WENTFROMBEINGTHE = " went from being the  ";
		THPROVIDEROF = " th provider of ";
		TONOTSELLINGANY = " to not selling any.";
		SHIPPEDPACKAGESENT = "Shipped Package sent ";
		WITH = " with ";
		YOUCANNOTDROPITEMS_ = "You cannot drop items while in a store.";
		YOUCANNOTEMPTYBUCKETS_ = "You cannot empty buckets while in a store.";
		YOUCANNOTCRAFTITEMS_ = "You cannot craft items while in a store.";
		SHOPPINGCARTSARENOTENABLED_ = "Shopping carts are not enabled in this world.";
		SHIPPINGISNOTENABLED_ = "Shipping is not enabled on this server.";
		YOUCANNOTOPENENDERCHESTS_ = "You cannot open Ender Chests while in a store.";
		RESTARTTHESERVER_VERSION = ". Restart the server to load the new version.";
		OFRE_UPDATECOMMAND = " of RealShopping is available for download. Update for new features and/or bugfixes with the rsupdate command.";
		OFRE_UPDATEINFO = " of RealShopping is available for download. Update for new features and/or bugfixes. You can get information about the new version with 'rsupdate info'";
		REALSHOPPINGINITIALIZED = "RealShopping initialized";
		REALSHOPPINGDISABLED = "RealShopping disabled";
		BOUGHTSTUFFFOR = " bought stuff for ";
		FROMYOURSTORE = " from your store ";
		OWNER = "Owner ";
		CANTAFFORDTOBUYITEMSFROMYOUFOR = " can't afford to buy items from you for ";
		WITHDRAWNFROMYOURACCOUNT = " withdrawn from your account.";
		YOUCANTAFFORDTOPAYTHEDELIVERYFEEOF = "You can't afford to pay the delivery fee of ";
		USESLEFT = " uses left";
		PRICES = " Prices: ";
		RSSTORESHELP = "Use rsstores with only the name of the store as argument to get some information about the store. For help, type any of these arguments: ";
		BUYFORHELP = ". Sets if and for how much of the sell price your store will buy items from players. 0 is default and means selling to your store is disabled.";
		COLLECTHELP = ". Collects items that have been stolen from (and then returned to) or sold to your store. If using the -c flag the items will spawn in a chast which you are standing on. You can limit the number of items returned by writing an number.";
		BANHELP = ". Banishes a player from your store forever. ";
		UNBANHELP = ". Unbanishes a previously banned player. ";
		KICKHELP = ". Kicks a player out of your store. You can use the -o flag to kick an offline player but do ONLY use it if you're about to remove the store, as the player won't be teleported out.";
		STARTSALEHELP = ". Starts a sale on the all or given items. Also cancels the last sale. Write items in this format: ";
		STARTSALEHELP2 = " and separate multiple items with commas. The percent argument can be any integer between 1 and 99";
		ENDSALEHELP = ". Ends all sales.";
		NOTIFICATIONSHELP = ". Sets if notifications are enabled or disabled for this store. Use without arguments to check current status.";
		ONCHANGEHELP = ". Sets if this store should notify you about changes in how well this store sells compared to others.";
		SETDEFAULTPRICESFOR = "Set default prices for ";
		THEREARENODEFAULTPRICES = "There are no default prices. Use /rsimport to import them, or see the plugin page for help.";
		QUITCONVERSATION = "Quit conversation.";
		WHICHFILEDOYOUWANTTOIMPORT_ = "Which file do you want to import a set of default prices from?";  
		ERROR_NO_XLSX_ = "Error: no files with the .xlsx extension found in the main directory or the RealShopping directory.";
		INTHEMAINDIRECTORY = " In the main directory:";
		INTHEREALSHOPPINGDIRECTORY = " In the RealShopping directory:";
		TYPETHECORRESPONDINGNUMBER_ = "Type the corresponding number to choose a file or ";
		TOCANCEL = " to cancel.";
		ERROR_INPUTISNOTAVALIDINTEGER = "Error: Input is not a valid integer.";
		CHOSENFILE = "Chosen file ";
		TYPE = "Type ";
		TOIMPORT_USERDEFINED_ = " to import from the user defined prices, or ";
		TOIMPORT_PROPOSITION_ = " to import from the proposition prices.";
		WRONGFILECHOSEN = "Wrong file chosen";
		IMPORTED = "Imported ";
		PRICESASDEFAULT = " prices as default.";
		ERRORCOULDNTIMPORTPRICES = "Error: Couldn't import prices.";
		DONE = "Done!";
		REALSHOPPINGUPDATEDTO = "RealShopping updated to ";
		X_ST = "st";
		X_ND = "nd";
		X_RD = "rd";
		X_TH = "th";
		//v0.44
		YOUWILLBENOTIFIEDIF = "You will be notified if ";
		LOSESGAINS = " loses/gains ";
		PLACES = " place(s).";
		THEPRICEWILLBELOWEREDINCREASED_ = "The price will be lowered/increased by ";
		PCNTIF = "% if ";
		WONTNOTIFY_ = " won't notify you about changes.";
		
		UNIT = "$";
		
		File f = new File(RealShopping.MANDIR + "langpacks/" + lang + ".xml");
		if(f.exists()) try {
			DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
			DocumentBuilder db = dbf.newDocumentBuilder();
			Document dom = db.parse(f);

			Element docEle = dom.getDocumentElement();
			NodeList nl = docEle.getElementsByTagName("*");
			if(nl != null && nl.getLength() > 0) {
				for(int i = 0 ; i < nl.getLength();i++) {
					Element el = (Element)nl.item(i);
					String name = el.getTagName();
					if(name.equals("UNIT")) UNIT = el.getAttribute("value");
					else if(name.equals("THISCOMMANDCANNOTBEUSEDFROMCONSOLE")) THISCOMMANDCANNOTBEUSEDFROMCONSOLE = el.getAttribute("value");
					else if(name.equals("REALSHOPPINGRELOADED")) REALSHOPPINGRELOADED = el.getAttribute("value");
					else if(name.equals("YOUENTERED")) YOUENTERED = el.getAttribute("value");
					else if(name.equals("YOULEFT")) YOULEFT = el.getAttribute("value");
					else if(name.equals("YOURENOTATTHEENTRANCEOFASTORE")) YOURENOTATTHEENTRANCEOFASTORE = el.getAttribute("value");
					else if(name.equals("YOURENOTATTHEEXITOFASTORE")) YOURENOTATTHEEXITOFASTORE = el.getAttribute("value");
					else if(name.equals("THEREARENOSTORESSET")) THEREARENOSTORESSET = el.getAttribute("value");
					else if(name.equals("YOUHAVENTPAIDFORALLYOURARTICLES")) YOUHAVENTPAIDFORALLYOURARTICLES = el.getAttribute("value");
					else if(name.equals("YOURENOTINSIDEASTORE")) YOURENOTINSIDEASTORE = el.getAttribute("value");
					else if(name.equals("YOUCANTAFFORDTOBUYTHINGSFOR")) YOUCANTAFFORDTOBUYTHINGSFOR = el.getAttribute("value");
					else if(name.equals("YOUBOUGHTSTUFFFOR")) YOUBOUGHTSTUFFFOR = el.getAttribute("value");
					else if(name.equals("THEREARENOPRICESSETFORTHISSTORE")) THEREARENOPRICESSETFORTHISSTORE = el.getAttribute("value");
					else if(name.equals("YOURARTICLESCOST")) YOURARTICLESCOST = el.getAttribute("value");
					else if(name.equals("TRYINGTOCHEATYOURWAYOUT")) TRYINGTOCHEATYOURWAYOUT = el.getAttribute("value");
					else if(name.equals("HAVEFUNINHELL")) HAVEFUNINHELL = el.getAttribute("value");
					else if(name.equals("ENTRANCEVARIABLESETTO")) ENTRANCEVARIABLESETTO = el.getAttribute("value");
					else if(name.equals("EXITVARIABLESETTO")) EXITVARIABLESETTO = el.getAttribute("value");
					else if(name.equals("WASCREATED")) WASCREATED = el.getAttribute("value");
					else if(name.equals("WASREMOVED")) WASREMOVED = el.getAttribute("value");
					else if(name.equals("WASNTFOUND")) WASNTFOUND = el.getAttribute("value");
					else if(name.equals("YOUARENOTTHEOWNEROFTHISSTORE")) YOUARENOTTHEOWNEROFTHISSTORE = el.getAttribute("value");
					else if(name.equals("THERESNOENTRANCESET")) THERESNOENTRANCESET = el.getAttribute("value");
					else if(name.equals("THERSNOEXITSET")) THERSNOEXITSET = el.getAttribute("value");
					else if(name.equals("YOUHAVETOUSETHESTOREARGUMENTWHENEXECUTINGTHISCOMMANDFROMCONSOLE")) YOUHAVETOUSETHESTOREARGUMENTWHENEXECUTINGTHISCOMMANDFROMCONSOLE = el.getAttribute("value");
					else if(name.equals("YOUHAVETOBEINASTOREIFNOTUSINGTHESTOREARGUMENT")) YOUHAVETOBEINASTOREIFNOTUSINGTHESTOREARGUMENT = el.getAttribute("value");
					else if(name.equals("THEPAGENUMBERMUSTBE1ORHIGHER")) THEPAGENUMBERMUSTBE1ORHIGHER = el.getAttribute("value");
					else if(name.equals("ISNOTAVALIDPAGENUMBER")) ISNOTAVALIDPAGENUMBER = el.getAttribute("value");
					else if(name.equals("YOUHAVETOBEINASTORETOUSETHISCOMMANDWITHTWOARGUENTS")) YOUHAVETOBEINASTORETOUSETHISCOMMANDWITHTWOARGUENTS = el.getAttribute("value");
					else if(name.equals("YOUHAVETOUSEALLTHREEARGUMENTSWHENEXECUTINGTHISCOMMANDFROMCONSOLE")) YOUHAVETOUSEALLTHREEARGUMENTSWHENEXECUTINGTHISCOMMANDFROMCONSOLE = el.getAttribute("value");
					else if(name.equals("PRICEFOR")) PRICEFOR = el.getAttribute("value");
					else if(name.equals("SETTO")) SETTO = el.getAttribute("value");
					else if(name.equals("ISNOTAPROPER_FOLLOWEDBYTHEPRICE_")) ISNOTAPROPER_FOLLOWEDBYTHEPRICE_ = el.getAttribute("value");
					else if(name.equals("ISNOTAPROPER_")) ISNOTAPROPER_ = el.getAttribute("value");
					else if(name.equals("REMOVEDPRICEFOR")) REMOVEDPRICEFOR = el.getAttribute("value");
					else if(name.equals("COULDNTFINDPRICEFOR")) COULDNTFINDPRICEFOR = el.getAttribute("value");
					else if(name.equals("YOUARENTPERMITTEDTOEMANAGETHISSTORE")) YOUARENTPERMITTEDTOEMANAGETHISSTORE = el.getAttribute("value");
					else if(name.equals("DOESNTEXIST")) DOESNTEXIST = el.getAttribute("value");
					else if(name.equals("CHESTCREATED")) CHESTCREATED = el.getAttribute("value");
					else if(name.equals("CHESTREMOVED")) CHESTREMOVED = el.getAttribute("value");
					else if(name.equals("ACHESTALREADYEXISTSONTHISLOCATION")) ACHESTALREADYEXISTSONTHISLOCATION = el.getAttribute("value");
					else if(name.equals("COULDNTFINDCHESTONTHISLOCATION")) COULDNTFINDCHESTONTHISLOCATION = el.getAttribute("value");
					else if(name.equals("ONLYADMINSTORESCANHAVESELFREFILLINGCHESTS")) ONLYADMINSTORESCANHAVESELFREFILLINGCHESTS = el.getAttribute("value");
					else if(name.equals("ADDED")) ADDED = el.getAttribute("value");
					else if(name.equals("REMOVED")) REMOVED = el.getAttribute("value");
					else if(name.equals("ITEMS")) ITEMS = el.getAttribute("value");
					else if(name.equals("THISCHESTDOESNTEXIST")) THISCHESTDOESNTEXIST = el.getAttribute("value");
					else if(name.equals("ONEORMOREOFTHEITEMIDSWERENOTINTEGERS")) ONEORMOREOFTHEITEMIDSWERENOTINTEGERS = el.getAttribute("value");
					else if(name.equals("YOUHAVETOBEINASTORETOUSETHISCOMMAND")) YOUHAVETOBEINASTORETOUSETHISCOMMAND = el.getAttribute("value");
					else if(name.equals("MOREITEMSONPAGE")) MOREITEMSONPAGE = el.getAttribute("value");
					else if(name.equals("THEREARENTTHATMANYPAGES")) THEREARENTTHATMANYPAGES = el.getAttribute("value");
					else if(name.equals("TRIEDTOSTEALFROMTHESTORE")) TRIEDTOSTEALFROMTHESTORE = el.getAttribute("value");
					else if(name.equals("WASTELEPORTEDTOHELL")) WASTELEPORTEDTOHELL = el.getAttribute("value");
					else if(name.equals("CREATINGASTORECOSTS")) CREATINGASTORECOSTS = el.getAttribute("value");
					else if(name.equals("YOUWEREJAILED")) YOUWEREJAILED = el.getAttribute("value");
					else if(name.equals("WASJAILED")) WASJAILED = el.getAttribute("value");
					else if(name.equals("YOUARENOLONGERINJAIL")) YOUARENOLONGERINJAIL  = el.getAttribute("value");
					else if(name.equals("UNJAILED")) UNJAILED = el.getAttribute("value");
					else if(name.equals("ISNOTJAILED")) ISNOTJAILED = el.getAttribute("value");
					else if(name.equals("ISNOTONLINE")) ISNOTONLINE = el.getAttribute("value");
					else if(name.equals("YOUAREBANNEDFROM")) YOUAREBANNEDFROM = el.getAttribute("value");
					else if(name.equals("YOUDONTOWNTHEITEMSYOUWANTTOSELL")) YOUDONTOWNTHEITEMSYOUWANTTOSELL = el.getAttribute("value");
					else if(name.equals("ADDEDTOSELLLIST")) ADDEDTOSELLLIST = el.getAttribute("value");
					else if(name.equals("THISSTOREDOESNTBUY")) THISSTOREDOESNTBUY = el.getAttribute("value");
					else if(name.equals("THISSTOREDOESNTBUYANYITEMS")) THISSTOREDOESNTBUYANYITEMS = el.getAttribute("value");
					else if(name.equals("CANCELLEDSELLINGITEMS")) CANCELLEDSELLINGITEMS = el.getAttribute("value");
					else if(name.equals("YOUDONTHAVEALLTHEITEMSYOUWANTEDTOSELL")) YOUDONTHAVEALLTHEITEMSYOUWANTEDTOSELL = el.getAttribute("value");
					else if(name.equals("SOLD")) SOLD = el.getAttribute("value");
					else if(name.equals("ITEMSFOR")) ITEMSFOR = el.getAttribute("value");
					else if(name.equals("YOUCANTSHIPANEMPTYCART")) YOUCANTSHIPANEMPTYCART = el.getAttribute("value");
					else if(name.equals("PACKAGEWAITINGTOBEDELIVERED")) PACKAGEWAITINGTOBEDELIVERED = el.getAttribute("value");
					else if(name.equals("YOUHAVENTBOUGHTANYTHING")) YOUHAVENTBOUGHTANYTHING = el.getAttribute("value");
					else if(name.equals("THERESNOPACKAGEWITHTHEID")) THERESNOPACKAGEWITHTHEID = el.getAttribute("value");
					else if(name.equals("YOUHAVENTGOTANYITEMSWAITINGTOBEDELIVERED")) YOUHAVENTGOTANYITEMSWAITINGTOBEDELIVERED = el.getAttribute("value");
					else if(name.equals("THEBLOCKYOUARESTANDINGONISNTACHEST")) THEBLOCKYOUARESTANDINGONISNTACHEST = el.getAttribute("value");
					else if(name.equals("THEREISA")) THEREISA = el.getAttribute("value");
					else if(name.equals("PCNTOFFSALEAT")) PCNTOFFSALEAT = el.getAttribute("value");
					else if(name.equals("ONSALE")) ONSALE = el.getAttribute("value");
					else if(name.equals("STORE")) STORE = el.getAttribute("value");
					else if(name.equals("OWNEDBY")) OWNEDBY = el.getAttribute("value");
					else if(name.equals("BUYSFOR")) BUYSFOR = el.getAttribute("value");
					else if(name.equals("PCNTOFORIGINAL")) PCNTOFORIGINAL = el.getAttribute("value");
					else if(name.equals("NOTBUYINGFROMPLAYERS")) NOTBUYINGFROMPLAYERS = el.getAttribute("value");
					else if(name.equals("YOUCANTUSEAVALUEBELLOW0")) YOUCANTUSEAVALUEBELLOW0 = el.getAttribute("value");
					else if(name.equals("YOUCANTUSEAVALUEOF0ORLESS")) YOUCANTUSEAVALUEOF0ORLESS = el.getAttribute("value");
					else if(name.equals("YOUCANTUSEAVALUEOVER100")) YOUCANTUSEAVALUEOVER100 = el.getAttribute("value");
					else if(name.equals("YOUCANTUSEAVALUEOF100ORMORE")) YOUCANTUSEAVALUEOF100ORMORE = el.getAttribute("value");
					else if(name.equals("NOITEMSARESOLDINTHESTORE")) NOITEMSARESOLDINTHESTORE = el.getAttribute("value");
					else if(name.equals("SALEENDED")) SALEENDED = el.getAttribute("value");
					else if(name.equals("HASA")) HASA = el.getAttribute("value");
					else if(name.equals("PCNTOFFSALERIGHTNOW")) PCNTOFFSALERIGHTNOW = el.getAttribute("value");
					else if(name.equals("PCNTOFF")) PCNTOFF = el.getAttribute("value");
					else if(name.equals("ISALREADYBANNEDFROMYOURSTORE")) ISALREADYBANNEDFROMYOURSTORE = el.getAttribute("value");
					else if(name.equals("ISNOLONGERBANNEDFROMYOURSTORE")) ISNOLONGERBANNEDFROMYOURSTORE = el.getAttribute("value");
					else if(name.equals("WASNTBANNEDFROMYOURSTORE")) WASNTBANNEDFROMYOURSTORE = el.getAttribute("value");
					else if(name.equals("BANNED")) BANNED = el.getAttribute("value");
					else if(name.equals("FROMSTORE")) FROMSTORE = el.getAttribute("value");
					else if(name.equals("YOUDONTHAVEPERMISSIONTOMANAGETHATSTORE")) YOUDONTHAVEPERMISSIONTOMANAGETHATSTORE = el.getAttribute("value");
					else if(name.equals("NOTHINGTOCOLLECT")) NOTHINGTOCOLLECT = el.getAttribute("value");
					else if(name.equals("FILLEDCHESTWITH")) FILLEDCHESTWITH = el.getAttribute("value");
					else if(name.equals("DROPPED")) DROPPED = el.getAttribute("value");
					else if(name.equals("YOUHAVEPACKAGESWITHIDS_")) YOUHAVEPACKAGESWITHIDS_ = el.getAttribute("value");
					else if(name.equals("YOUDONTHAVEANYPACKAGESTOPICKUP")) YOUDONTHAVEANYPACKAGESTOPICKUP = el.getAttribute("value");
					else if(name.equals("TOPICKUP")) TOPICKUP = el.getAttribute("value");
					else if(name.equals("YOUHAVETOSPECIFYTHEID_")) YOUHAVETOSPECIFYTHEID_ = el.getAttribute("value");
					else if(name.equals("THECONTENTSOFTHEPACKAGEARE")) THECONTENTSOFTHEPACKAGEARE = el.getAttribute("value");
					else if(name.equals("WHITELISTMODEALREADYSET")) WHITELISTMODEALREADYSET = el.getAttribute("value");
					else if(name.equals("BLACKLISTMODEALREADYSET")) BLACKLISTMODEALREADYSET = el.getAttribute("value");
					else if(name.equals("SETWHITELISTMODE")) SETWHITELISTMODE = el.getAttribute("value");
					else if(name.equals("SETBLACKLISTMODE")) SETBLACKLISTMODE = el.getAttribute("value");
					else if(name.equals("REMOVEDONEOFTHE")) REMOVEDONEOFTHE = el.getAttribute("value");
					else if(name.equals("TELEPORTLOCATIONS")) TELEPORTLOCATIONS = el.getAttribute("value");
					else if(name.equals("THEREISNO")) THEREISNO = el.getAttribute("value");
					else if(name.equals("TELEPORTLOCATIONWITHITSCENTERHERE")) TELEPORTLOCATIONWITHITSCENTERHERE = el.getAttribute("value");
					else if(name.equals("OLDRADIUSVALUE")) OLDRADIUSVALUE = el.getAttribute("value");
					else if(name.equals("REPLACEDWITH")) REPLACEDWITH = el.getAttribute("value");
					else if(name.equals("TELEPORTLOCATIONWITHARADIUSOF")) TELEPORTLOCATIONWITHARADIUSOF = el.getAttribute("value");
					else if(name.equals("ISNOTANINTEGER")) ISNOTANINTEGER = el.getAttribute("value");
					else if(name.equals("ISNOTAVALIDARGUMENT")) ISNOTAVALIDARGUMENT = el.getAttribute("value");
					else if(name.equals("YOUARENTALLOWEDTOTELEPORTTHERE")) YOUARENTALLOWEDTOTELEPORTTHERE = el.getAttribute("value");
					else if(name.equals("SELLINGTOSTORESISNOTENABLEDONTHISSERVER")) SELLINGTOSTORESISNOTENABLEDONTHISSERVER = el.getAttribute("value");
					else if(name.equals("ISNOTINYOURSTORE")) ISNOTINYOURSTORE = el.getAttribute("value");
					else if(name.equals("WASKICKEDFROMYOURSTORE")) WASKICKEDFROMYOURSTORE = el.getAttribute("value");
					else if(name.equals("PLAYER")) PLAYER = el.getAttribute("value");
					else if(name.equals("ISNTONLINEKICK")) ISNTONLINEKICK = el.getAttribute("value");
					else if(name.equals("PLAYERSINSTORE")) PLAYERSINSTORE = el.getAttribute("value");
					else if(name.equals("STORENOTEMPTY")) STORENOTEMPTY = el.getAttribute("value");
					else if(name.equals("PACKAGESENT")) PACKAGESENT = el.getAttribute("value");
					else if(name.equals("FROM")) FROM = el.getAttribute("value");
					else if(name.equals("INWORLD")) INWORLD = el.getAttribute("value");
					else if(name.equals("YOUCANTUSETHATITEMINSTORE")) YOUCANTUSETHATITEMINSTORE = el.getAttribute("value");
					else if(name.equals("THISCHESTISPROTECTED")) THISCHESTISPROTECTED = el.getAttribute("value");
					//v0.43
					else if(name.equals("SELLTOSTORE")) SELLTOSTORE = el.getAttribute("value");
					else if(name.equals("ENABLEDNOTIFICATIONSFOR")) ENABLEDNOTIFICATIONSFOR = el.getAttribute("value");
					else if(name.equals("DISABLEDNOTIFICATIONSFOR")) DISABLEDNOTIFICATIONSFOR = el.getAttribute("value");
					else if(name.equals("USAGE")) USAGE = el.getAttribute("value");
					else if(name.equals("NOTIFICATIONSARE")) NOTIFICATIONSARE = el.getAttribute("value");
					else if(name.equals("ON")) ON = el.getAttribute("value");
					else if(name.equals("OFF")) OFF = el.getAttribute("value");
					else if(name.equals("SKIPPSIGN")) SKIPPSIGN = el.getAttribute("value");
					else if(name.equals("YOUWONTGETNOTIFIEDWHENYOURSTORE")) YOUWONTGETNOTIFIEDWHENYOURSTORE = el.getAttribute("value");
					else if(name.equals("BECOMESMOREORLESSPOPULAR")) BECOMESMOREORLESSPOPULAR = el.getAttribute("value");
					else if(name.equals("YOUWILLGETNOTIFIEDWHENYOURSTORE")) YOUWILLGETNOTIFIEDWHENYOURSTORE = el.getAttribute("value");
					else if(name.equals("BECOMESATLEAST")) BECOMESATLEAST = el.getAttribute("value");
					else if(name.equals("PLACESMOREORLESSPOPULAR")) PLACESMOREORLESSPOPULAR = el.getAttribute("value");
					else if(name.equals("WHERETRESHOLDIS_")) WHERETRESHOLDIS_ = el.getAttribute("value");
					else if(name.equals("ANDTHEPRICESWILLBE_")) ANDTHEPRICESWILLBE_ = el.getAttribute("value");
					else if(name.equals("WHERETRESHOLDIS_CHANGES_")) WHERETRESHOLDIS_CHANGES_ = el.getAttribute("value");
					else if(name.equals("ANDPERCENTIS_")) ANDPERCENTIS_ = el.getAttribute("value");
					else if(name.equals("AI_ISNOTENABLED_")) AI_ISNOTENABLED_ = el.getAttribute("value");
					else if(name.equals("SETMINIMALANDMAXIMALPRICESFOR")) SETMINIMALANDMAXIMALPRICESFOR = el.getAttribute("value");
					else if(name.equals("OLDPRICESREPLACEDWITHPRICESFROM")) OLDPRICESREPLACEDWITHPRICESFROM = el.getAttribute("value");
					else if(name.equals("OLDPRICESREPLACEDWITHTHELOWEST_")) OLDPRICESREPLACEDWITHTHELOWEST_ = el.getAttribute("value");
					else if(name.equals("CLEAREDALLPRICESFOR")) CLEAREDALLPRICESFOR = el.getAttribute("value");
					else if(name.equals("HASAMINIMALPRICEOF")) HASAMINIMALPRICEOF = el.getAttribute("value");
					else if(name.equals("ANDAMAXIMALPRICEOF")) ANDAMAXIMALPRICEOF = el.getAttribute("value");
					else if(name.equals("FOR")) FOR = el.getAttribute("value");
					else if(name.equals("DOESNTHAVEAMINIMALANDMAXIMALPRICEFOR")) DOESNTHAVEAMINIMALANDMAXIMALPRICEFOR = el.getAttribute("value");
					else if(name.equals("CLEAREDMINIMALANDMAXIMALPRICESFOR")) CLEAREDMINIMALANDMAXIMALPRICESFOR = el.getAttribute("value");
					else if(name.equals("DIDNTHAVEAMINIMALANDMAXIMALPRICEFOR")) DIDNTHAVEAMINIMALANDMAXIMALPRICEFOR = el.getAttribute("value");
					else if(name.equals("ISNOTAPROPERARGUMENT")) ISNOTAPROPERARGUMENT = el.getAttribute("value");
					else if(name.equals("YOUCANTNAMEASTORETHAT")) YOUCANTNAMEASTORETHAT = el.getAttribute("value");
					else if(name.equals("HIGHLIGHTED5LOCATIONSFOR5SECONDS")) HIGHLIGHTED5LOCATIONSFOR5SECONDS = el.getAttribute("value");
					else if(name.equals("NOLOCATIONSTOHIGHLIGHT")) NOLOCATIONSTOHIGHLIGHT = el.getAttribute("value");
					else if(name.equals("THISCHESTISALREADYPROTECTED")) THISCHESTISALREADYPROTECTED = el.getAttribute("value");
					else if(name.equals("MADECHESTPROTECTED")) MADECHESTPROTECTED = el.getAttribute("value");
					else if(name.equals("UNPROTECTEDCHEST")) UNPROTECTEDCHEST = el.getAttribute("value");
					else if(name.equals("THISCHESTISNTPROTECTED")) THISCHESTISNTPROTECTED = el.getAttribute("value");
					else if(name.equals("READINGDESCRIPTION")) READINGDESCRIPTION = el.getAttribute("value");
					else if(name.equals("THISISTHENEWESTVERSION")) THISISTHENEWESTVERSION = el.getAttribute("value");
					else if(name.equals("SUCCESSFULUPDATE")) SUCCESSFULUPDATE = el.getAttribute("value");
					else if(name.equals("UPDATEFAILED")) UPDATEFAILED = el.getAttribute("value");
					else if(name.equals("YOUARENTPERMITTEDTOUSETHISCOMMAND")) YOUARENTPERMITTEDTOUSETHISCOMMAND = el.getAttribute("value");
					else if(name.equals("YOUCANTCOLLECT_YOUDONOTOWN")) YOUCANTCOLLECT_YOUDONOTOWN = el.getAttribute("value");
					else if(name.equals("YOUCANTCOLLECT_SERVER")) YOUCANTCOLLECT_SERVER = el.getAttribute("value");
					else if(name.equals("THELASTHOUR")) THELASTHOUR = el.getAttribute("value");
					else if(name.equals("YESTERDAY")) YESTERDAY = el.getAttribute("value");
					else if(name.equals("LASTWEEK")) LASTWEEK = el.getAttribute("value");
					else if(name.equals("LASTMONTH")) LASTMONTH = el.getAttribute("value");
					else if(name.equals("YOURSTORE")) YOURSTORE = el.getAttribute("value");
					else if(name.equals("ISNOWTHE")) ISNOWTHE = el.getAttribute("value");
					else if(name.equals("SINCE")) SINCE = el.getAttribute("value");
					else if(name.equals("PROVIDEROF")) PROVIDEROF = el.getAttribute("value");
					else if(name.equals("RAISEDTHEPRICEFOR")) RAISEDTHEPRICEFOR = el.getAttribute("value");
					else if(name.equals("LOWEREDTHEPRICEFOR")) LOWEREDTHEPRICEFOR = el.getAttribute("value");
					else if(name.equals("BY")) BY = el.getAttribute("value");
					else if(name.equals("TO")) TO = el.getAttribute("value");
					else if(name.equals("WENTFROMBEINGTHE")) WENTFROMBEINGTHE = el.getAttribute("value");
					else if(name.equals("THPROVIDEROF")) THPROVIDEROF = el.getAttribute("value");
					else if(name.equals("TONOTSELLINGANY")) TONOTSELLINGANY = el.getAttribute("value");
					else if(name.equals("SHIPPEDPACKAGESENT")) SHIPPEDPACKAGESENT = el.getAttribute("value");
					else if(name.equals("WITH")) WITH = el.getAttribute("value");
					else if(name.equals("YOUCANNOTDROPITEMS_")) YOUCANNOTDROPITEMS_ = el.getAttribute("value");
					else if(name.equals("YOUCANNOTEMPTYBUCKETS_")) YOUCANNOTEMPTYBUCKETS_ = el.getAttribute("value");
					else if(name.equals("YOUCANNOTCRAFTITEMS_")) YOUCANNOTCRAFTITEMS_ = el.getAttribute("value");
					else if(name.equals("SHOPPINGCARTSARENOTENABLED_")) SHOPPINGCARTSARENOTENABLED_ = el.getAttribute("value");
					else if(name.equals("SHIPPINGISNOTENABLED_")) SHIPPINGISNOTENABLED_ = el.getAttribute("value");
					else if(name.equals("YOUCANNOTOPENENDERCHESTS_")) YOUCANNOTOPENENDERCHESTS_ = el.getAttribute("value");
					else if(name.equals("RESTARTTHESERVER_VERSION")) RESTARTTHESERVER_VERSION = el.getAttribute("value");
					else if(name.equals("OFRE_UPDATECOMMAND")) OFRE_UPDATECOMMAND = el.getAttribute("value");
					else if(name.equals("OFRE_UPDATEINFO")) OFRE_UPDATEINFO = el.getAttribute("value");
					else if(name.equals("REALSHOPPINGINITIALIZED")) REALSHOPPINGINITIALIZED = el.getAttribute("value");
					else if(name.equals("REALSHOPPINGDISABLED")) REALSHOPPINGDISABLED = el.getAttribute("value");
					else if(name.equals("BOUGHTSTUFFFOR")) BOUGHTSTUFFFOR = el.getAttribute("value");
					else if(name.equals("FROMYOURSTORE")) FROMYOURSTORE = el.getAttribute("value");
					else if(name.equals("OWNER")) OWNER = el.getAttribute("value");
					else if(name.equals("CANTAFFORDTOBUYITEMSFROMYOUFOR")) CANTAFFORDTOBUYITEMSFROMYOUFOR = el.getAttribute("value");
					else if(name.equals("WITHDRAWNFROMYOURACCOUNT")) WITHDRAWNFROMYOURACCOUNT = el.getAttribute("value");
					else if(name.equals("YOUCANTAFFORDTOPAYTHEDELIVERYFEEOF")) YOUCANTAFFORDTOPAYTHEDELIVERYFEEOF = el.getAttribute("value");
					else if(name.equals("USESLEFT")) USESLEFT = el.getAttribute("value");
					else if(name.equals("PRICES")) PRICES = el.getAttribute("value");
					else if(name.equals("RSSTORESHELP")) RSSTORESHELP = el.getAttribute("value");
					else if(name.equals("BUYFORHELP")) BUYFORHELP = el.getAttribute("value");
					else if(name.equals("COLLECTHELP")) COLLECTHELP = el.getAttribute("value");
					else if(name.equals("BANHELP")) BANHELP = el.getAttribute("value");
					else if(name.equals("UNBANHELP")) UNBANHELP = el.getAttribute("value");
					else if(name.equals("KICKHELP")) KICKHELP = el.getAttribute("value");
					else if(name.equals("STARTSALEHELP")) STARTSALEHELP = el.getAttribute("value");
					else if(name.equals("STARTSALEHELP2")) STARTSALEHELP2 = el.getAttribute("value");
					else if(name.equals("ENDSALEHELP")) ENDSALEHELP = el.getAttribute("value");
					else if(name.equals("NOTIFICATIONSHELP")) NOTIFICATIONSHELP = el.getAttribute("value");
					else if(name.equals("ONCHANGEHELP")) ONCHANGEHELP = el.getAttribute("value");
					else if(name.equals("SETDEFAULTPRICESFOR")) SETDEFAULTPRICESFOR = el.getAttribute("value");
					else if(name.equals("THEREARENODEFAULTPRICES")) THEREARENODEFAULTPRICES = el.getAttribute("value");
					else if(name.equals("QUITCONVERSATION")) QUITCONVERSATION = el.getAttribute("value");
					else if(name.equals("WHICHFILEDOYOUWANTTOIMPORT_")) WHICHFILEDOYOUWANTTOIMPORT_ = el.getAttribute("value");
					else if(name.equals("ERROR_NO_XLSX_")) ERROR_NO_XLSX_ = el.getAttribute("value");
					else if(name.equals("INTHEMAINDIRECTORY")) INTHEMAINDIRECTORY = el.getAttribute("value");
					else if(name.equals("INTHEREALSHOPPINGDIRECTORY")) INTHEREALSHOPPINGDIRECTORY = el.getAttribute("value");
					else if(name.equals("TYPETHECORRESPONDINGNUMBER_")) TYPETHECORRESPONDINGNUMBER_ = el.getAttribute("value");
					else if(name.equals("TOCANCEL")) TOCANCEL = el.getAttribute("value");
					else if(name.equals("ERROR_INPUTISNOTAVALIDINTEGER")) ERROR_INPUTISNOTAVALIDINTEGER = el.getAttribute("value");
					else if(name.equals("CHOSENFILE")) CHOSENFILE = el.getAttribute("value");
					else if(name.equals("TYPE")) TYPE = el.getAttribute("value");
					else if(name.equals("TOIMPORT_USERDEFINED_")) TOIMPORT_USERDEFINED_ = el.getAttribute("value");
					else if(name.equals("TOIMPORT_PROPOSITION_")) TOIMPORT_PROPOSITION_ = el.getAttribute("value");
					else if(name.equals("WRONGFILECHOSEN")) WRONGFILECHOSEN = el.getAttribute("value");
					else if(name.equals("IMPORTED")) IMPORTED = el.getAttribute("value");
					else if(name.equals("PRICESASDEFAULT")) PRICESASDEFAULT = el.getAttribute("value");
					else if(name.equals("ERRORCOULDNTIMPORTPRICES")) ERRORCOULDNTIMPORTPRICES = el.getAttribute("value");
					else if(name.equals("DONE")) DONE = el.getAttribute("value");
					else if(name.equals("REALSHOPPINGUPDATEDTO")) REALSHOPPINGUPDATEDTO = el.getAttribute("value");
					else if(name.equals("X_ST")) X_ST = el.getAttribute("value");
					else if(name.equals("X_ND")) X_ND = el.getAttribute("value");
					else if(name.equals("X_RD")) X_RD = el.getAttribute("value");
					else if(name.equals("X_TH")) X_TH = el.getAttribute("value");
					//v0.44
					else if(name.equals(YOUWILLBENOTIFIEDIF)) YOUWILLBENOTIFIEDIF = el.getAttribute("value");
					else if(name.equals(LOSESGAINS)) LOSESGAINS = el.getAttribute("value");
					else if(name.equals(PLACES)) PLACES = el.getAttribute("value");
					else if(name.equals(THEPRICEWILLBELOWEREDINCREASED_)) THEPRICEWILLBELOWEREDINCREASED_ = el.getAttribute("value");
					else if(name.equals(PCNTIF)) PCNTIF = el.getAttribute("value");
					else if(name.equals(WONTNOTIFY_)) WONTNOTIFY_ = el.getAttribute("value");
				}
				RealShopping.log.info("Loaded " + lang + " language pack.");
			}
		} catch (SAXException e) {
			e.printStackTrace();
			RealShopping.log.info("Failed while loading " + lang + " language pack.");
		} catch (IOException e) {
			e.printStackTrace();
			RealShopping.log.info("Failed while loading " + lang + " language pack.");
		} catch (ParserConfigurationException e) {
			e.printStackTrace();
			RealShopping.log.info("Failed while loading " + lang + " language pack.");
		} catch (Exception e) {
			e.printStackTrace();
			RealShopping.log.info("Failed while loading " + lang + " language pack.");
		}
		else RealShopping.log.info("Loaded default language pack.");
	}
}
